name:                hw-dsv
version:             0.2.1
github:              "haskell-works/hw-dsv"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com"
copyright:           "2018 John Ky"

extra-source-files:
- README.md
- ChangeLog.md
- data/bench/data-0001000.csv
- cbits/simd.h

# Metadata used when publishing your package
synopsis:            Unbelievably fast streaming DSV file parser
category:            Text, Web, CSV

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/haskell-works/hw-dsv#readme>

tested-with:         GHC == 8.4.3, GHC == 8.2.2, GHC == 8.0.2, GHC == 7.10.3

dependencies:
- base                  >= 4.7      && < 5
- bits-extra            >= 0.0.1.2  && < 0.1
- bytestring            >= 0.10     && < 0.11
- deepseq               >= 1.4      && < 1.5
- hw-bits               >= 0.7.0.2  && < 0.8
- hw-rankselect         >= 0.12.0.2 && < 0.13
- hw-rankselect-base    >= 0.3.2.0  && < 0.4
- hw-prim               >= 0.6.2.0  && < 0.7
- hw-simd               >= 0.0.0.3  && < 0.1
- vector                >= 0.12.0.1 && < 0.13

library:
  source-dirs: src
  build-tools:
  - c2hs
  c-sources:
  - cbits/simd.c
  include-dirs:
  - cbits

executables:
  hw-dsv:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw-dsv
    - hedgehog                >= 0.5        && < 0.7
    - lens                    >= 4.15       && < 5
    - optparse-applicative    >= 0.13       && < 0.15
    - resourcet               >= 1.1        && < 1.3

tests:
  hw-dsv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory               >= 1.2.2      && < 1.4
    - hw-dsv
    - hedgehog                >= 0.5        && < 0.7
    - hspec                   >= 2.4        && < 3
    - hw-hspec-hedgehog       >= 0.1.0.4    && < 0.2
    - text                    >= 1.2.2      && < 2.0
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover

  hw-dsv-space:
    main:               Space.hs
    source-dirs:        weigh
    dependencies:
      - cassava               >= 0.5.1.0    && < 0.6
      - hw-dsv
      - weigh                 >= 0.0.6      && < 0.1
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -msse4.2
    dependencies:
    - cassava               >= 0.5.1.0    && < 0.6
    - criterion             >= 1.4.1.0    && < 1.5
    - directory             >= 1.3.1.5    && < 1.4
    - hw-dsv
    - mmap                  >= 0.5.9      && < 0.6

ghc-options:
- -O2 -Wall

when:
- condition: flag(sse42)
  cc-options:
  - -msse4.2
  ghc-options:
  - -msse4.2
- condition: flag(bmi2)
  cc-options:
  - -mbmi2
  - -DBMI2_ENABLED
- condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
  ghc-options:
  - -mbmi2
  - -msse4.2
- condition:  flag(avx2)
  cc-options:
  - -mavx2
  - -DAVX2_ENABLED
- condition: (flag(avx2)) && (impl(ghc >=8.4.1))
  ghc-options:
  - -mbmi2
  - -msse4.2
  cpp-options:
  - -DBMI2_ENABLED
  - -DAVX2_ENABLED
- condition: (impl(ghc >=8.0.1))
  ghc-options:
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
- condition: (!impl(ghc >=8.0.1))
  dependencies:
    - transformers          >= 0.4        && < 0.6
    - semigroups            >= 0.8.4      && < 0.19

flags:
  sse42:
    description: Enable SSE 4.2 optimisations.
    manual: false
    default: true

  bmi2:
    description: Enable bmi2 instruction set
    manual: false
    default: false

  avx2:
    description: Enable avx2 instruction set
    manual: false
    default: false
